//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class destektalepleri
    {
        public long id { get; set; }
        public string konubasligi { get; set; }
        public string konuicerigi { get; set; }
        public string uygulama { get; set; }
        public string destekverilenpersonel { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string cezaevi { get; set; }
        public string personeltelefon { get; set; }
        public string destekveren { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
