//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        public long id { get; set; }
        public string kullaniciepost { get; set; }
        public string kullaniciadi { get; set; }
        public string kullanicisoyadi { get; set; }
        public string kullanicisifre { get; set; }
        public Nullable<long> yetki { get; set; }
    }
}
