//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class stok
    {
        public long id { get; set; }
        public Nullable<long> urun { get; set; }
        public Nullable<long> depo { get; set; }
        public Nullable<long> raf { get; set; }
        public string aciklama { get; set; }
        public Nullable<long> adet { get; set; }
    
        public virtual depo depo1 { get; set; }
        public virtual raf raf1 { get; set; }
        public virtual urunler urunler { get; set; }
    }
}
